[global]
timeout = 5000
device_name = "hp-note"
default_folder = "/tmp"

[local_discovery]
enabled = 1
port = 21026
frequency = 10

[global_discovery]
enabled = 1
announce_url = "https://discovery.syncthing.net/"
device_id = "LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW"
cert_file = "~/.config/syncthing/cert.pem"
key_file = "~/.config/syncthing/key.pem"
rx_buff_size = 32768
timeout = 3000

[upnp]
discovery_attempts = 2
max_wait = 1
timeout = 10
external_port = 22001
rx_buff_size = 65536

[bep]
# 32 MB
rx_buff_size = 33554432

[devices]
    [devices.1]
    id = "KHQNO2S-5QSILRK-YX4JZZ4-7L77APM-QNVGZJT-EKU7IFI-PNEPBMY-4MXFMQD"
    name = "tmp_cl"
    address = "dynamic"
    introducer = true
    auto_accept = true

[folders]
    [folder.1]
        id = "my_folder"
        name = "my_folder"
        path = "/data"
        shared = ["tmp_cl"]

    [folder.2]
        id = "tex"
        name = "tex"
        path = "/home/b/development/tex"

