[bep]
connect_timeout = 5000
ping_timeout = 500
rx_buff_size = 33554432

[global_discovery]
announce_url = 'https://discovery.syncthing.net/'
cert_file = '/home/b/.config/syncthing/cert.pem'
device_id = 'LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW'
enabled = true
key_file = '/home/b/.config/syncthing/key.pem'
rx_buff_size = 32768
timeout = 3000

[local_discovery]
enabled = true
frequency = 10
port = 21026

[main]
default_location = '/tmp/syncspirit'
device_name = 'hp-note'
ignored_devices = []
timeout = 5000

[tui]
key_config = 'c'
key_help = '?'
key_less_logs = '-'
key_more_logs = '+'
key_quit = 'q'
refresh_interval = 50

[upnp]
discovery_attempts = 2
external_port = 22001
max_wait = 1
rx_buff_size = 65536
timeout = 10

[[device]]
auto_accept = false
cert_name = 'syncthing'
compression = 2
id = 'KUEQE66-JJ7P6AD-BEHD4ZW-GPBNW6Q-Y4C3K4Y-X44WJWZ-DVPIDXS-UDRJMA7'
introducer = false
name = 'synth-orig'
paused = false
skip_introduction_removals = false

    [[device.ignored_folder]]
    id = 'ig6gw-nhbjt'
    label = 'empty-folder'

    [[device.ignored_folder]]
    id = 'nagkw-srrjz'
    label = 'Sync'

[[folder]]
devices = [ 'KUEQE66-JJ7P6AD-BEHD4ZW-GPBNW6Q-Y4C3K4Y-X44WJWZ-DVPIDXS-UDRJMA7' ]
disable_temp_indixes = false
folder_type = 3
id = 'e59yo-b73fz'
ignore_delete = false
ignore_permissions = false
label = 'sample-folder'
path = '/tmp/syncspirit/sample-folder'
paused = false
pull_order = 0
read_only = false
rescan_interval = 3600
watched = true
