[bep]
connect_timeout = 5000
rx_buff_size = 33554432
rx_timeout = 300000
tx_timeout = 10000

[dialer]
enabled = true
redial_timeout = 300000

[global_discovery]
announce_url = 'https://discovery.syncthing.net/'
cert_file = '/home/b/.config/syncthing/cert.pem'
device_id = 'LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW'
enabled = true
key_file = '/home/b/.config/syncthing/key.pem'
rx_buff_size = 32768
timeout = 3000

[local_discovery]
enabled = true
frequency = 10
port = 21026

[main]
default_location = '/tmp/syncspirit'
device_name = 'hp-note'
ignored_devices = []
timeout = 5000

[tui]
key_config = 'c'
key_help = '?'
key_less_logs = '-'
key_more_logs = '+'
key_quit = 'q'
refresh_interval = 50

[upnp]
discovery_attempts = 2
external_port = 22001
max_wait = 1
rx_buff_size = 65536
timeout = 10
